UPLOAD_DIR = "uploads/"
csv_file_path = "Output.csv"
api_key = "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"
csv_delimiter = "~"
system_prompt_ingredients = "You will be provided with a block of text, and your task is to extract ingredients from it. without any comments | only ingredients"
system_prompt_energy = "You will be provided with a block of text, and your task is to extract energy value from it. without any comments | only energy value"
